Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 8
Rules claiming more threads will be scaled down.
Provided resources: mem_mb=16000, mem_mib=15259, disk_mb=1000, disk_mib=954, cpus=8, time_min=120, gpu=0
Select jobs to execute...

[Sun Apr 23 15:33:06 2023]
rule mriqc:
    input: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/sub-ctrl18/ses-a
    output: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc/sub-ctrl18
    log: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/fmriprep/sub-ctrl18.html
    jobid: 0
    reason: Missing output files: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc/sub-ctrl18
    wildcards: resultsdir=/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross, subject=ctrl18
    threads: 8
    resources: mem_mb=16000, mem_mib=15259, disk_mb=1000, disk_mib=954, tmpdir=/dev/shm/jobs/34739910, cpus=8, time_min=120, gpu=0

mriqc /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc participant --participant-label ctrl18 --mem-gb 16000 --nprocs 8 --no-sub -w /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work 
Activating singularity image /scale_wlg_persistent/filesets/project/uoa03264/fmri_workflow/.snakemake/singularity/62b788ffbe002df7aabb5b5b0b010147.simg
230423-03:33:17,811 cli IMPORTANT:
	 
    Running MRIQC version 23.0.1:
      * BIDS dataset path: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids.
      * Output folder: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc.
      * Analysis levels: ['participant'].

230423-03:38:29,977 cli WARNING:
	 Building bold report: no exclude index was found
230423-03:40:26,90 cli WARNING:
	 Building bold report: no exclude index was found
230423-03:52:51,171 nipype.workflow WARNING:
	 Storing result file without outputs
230423-03:52:51,191 nipype.workflow WARNING:
	 [Node] Error on "mriqc_wf.anatMRIQC.segmentation" (/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation)
230423-03:52:52,777 nipype.workflow ERROR:
	 Node segmentation.a0 failed to run on host wmc005.
230423-03:52:52,778 nipype.workflow ERROR:
	 Saving crash info to /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc/logs/crash-20230423-035252-jmcg465-segmentation.a0-53eadf30-c718-4fb7-af3f-5fb7de7a19da.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node segmentation.

Cmdline:
	fast -t 1 -o segment -g -S 1 /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/clipped_corrected_masked.nii.gz
Stdout:

Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/segment_seg.nii.gz' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/segment_seg.nii.gz' for output 'tissue_class_map' of a FAST interface


Traceback (most recent call last):
  File "/opt/conda/bin/mriqc", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/mriqc/cli/run.py", line 167, in main
    mriqc_wf.run(**_plugin)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 184, in run
    self._clean_queue(jobid, graph, result=result)
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 256, in _clean_queue
    raise RuntimeError("".join(result["traceback"]))
RuntimeError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/mriqc/engine/plugin.py", line 60, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.9/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node segmentation.

Cmdline:
	fast -t 1 -o segment -g -S 1 /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/clipped_corrected_masked.nii.gz
Stdout:

Stderr:
	Killed
Traceback:
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 454, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/opt/conda/lib/python3.9/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'tissue_class_map' trait of a FASTOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/segment_seg.nii.gz' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 401, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/conda/lib/python3.9/site-packages/nipype/interfaces/base/core.py", line 461, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work/mriqc_wf/anatMRIQC/_in_file_..nesi..nobackup..uoa03264..fMRIpipeline_data..processed_test_cross..bids..sub-ctrl18..ses-a..anat..sub-ctrl18_ses-a_run-001_T1w.nii.gz/segmentation/segment_seg.nii.gz' for output 'tissue_class_map' of a FAST interface


[Sun Apr 23 16:00:10 2023]
Error in rule mriqc:
    jobid: 0
    input: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/sub-ctrl18/ses-a
    output: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc/sub-ctrl18
    log: /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/fmriprep/sub-ctrl18.html (check log file(s) for error details)
    shell:
        mriqc /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc participant --participant-label ctrl18 --mem-gb 16000 --nprocs 8 --no-sub -w /nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/work 
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job mriqc since they might be corrupted:
/nesi/nobackup/uoa03264/fMRIpipeline_data/processed_test_cross/bids/derivatives/mriqc/sub-ctrl18
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
slurmstepd: error: Detected 1 oom-kill event(s) in StepId=34739910.batch. Some of your processes may have been killed by the cgroup out-of-memory handler.
